#define KBD_IRQ 1
#define KBC_OUT_BUF 0x60
#define KBC_STAT_REG 0x64
#define KBC_IN_BUF_CMD 0x64
#define KBC_IN_BUF_ARG 0x60

#define KBD_ESC_KEY 0x81
#define KBD_FIRST_OF_TWO_BYTES 0xE0
#define KBD_KEY_IS_MAKE(byte) !(byte & BIT(7))

#define KBC_STAT_OBF BIT(0)
#define KBC_STAT_IBF BIT(1)
#define KBC_STAT_AUX BIT(5)
#define KBC_STAT_ERR (BIT(6) | BIT(7))

#define KBC_CMD_READ_BYTE 0x20
#define KBC_CMD_WRITE_BYTE 0x60
#define KBC_CMD_WRITE_MOUSE_BYTE 0xD4

#define KBC_CMD_BYTE_DIS2 BIT(5)
#define KBC_CMD_BYTE_DIS BIT(4)
#define KBC_CMD_BYTE_INT2 BIT(1)
#define KBC_CMD_BYTE_INT BIT(0)

#define MOUSE_BYTE1_Y_OVFL BIT(7)
#define MOUSE_BYTE1_X_OVFL BIT(6)
#define MOUSE_BYTE1_MSBYDELTA BIT(5)
#define MOUSE_BYTE1_MSBXDELTA BIT(4)
#define MOUSE_BYTE1_MIDDLEBUTTON BIT(2)
#define MOUSE_BYTE1_RIGHTBUTTON BIT(1)
#define MOUSE_BYTE1_LEFTBUTTON BIT(0)
#define MOUSE_BYTE1_FLAG BIT(3)

#define MOUSE_CMD_ARG_ENABLE_DATA_REPORTING 0xF4
#define MOUSE_CMD_ARG_DISABLE_DATA_REPORTING 0xF5
#define MOUSE_CMD_ARG_ENABLE_STREAM_MODE 0xEA
#define MOUSE_CMD_ARG_ENABLE_REMOTE_MODE 0xF0
#define MOUSE_CMD_ARG_READ_DATA 0xEB

#define MOUSE_RESPONSE_ACK 0xFA

int mouse_send_cmd(uint8_t arg);