PROG = lab2 
SRCS = lab2.c timer.c

# list of library dependencies (for Lab 2, only LCF library)
DPADD += ${LIBLCF}
LDADD += -llcf -l:../common/lcfextd.a

# include LCOM's makefile that does all the "heavy lifting"
.include <minix.lcom.mk>