# list of library dependencies (for Lab 2, only LCF library)
DPADD += ${LIBLCF}
LDADD += -llcf

PROG = lcfextd
SRCS = ih_vec.c lib.c

# include LCOM's makefile that does all the "heavy lifting"
.include <minix.lcom.mk>